### ISSUE TITLE
3D pie now working when used as an element in HTML page

### ISSUE THREAD

**Issue by tanmay-mehrotra** [fusioncharts/angularjs-fusioncharts#1]
I recently observed then when I am using :
< fc-chart fc-width="600" fc-height="400" fc-type="pie3d", fc-datasource="{{dataSource}}" > < /fc-chart >
chart is not getting rendered.
However, when I use it as an attribute it working as expected:
< div fc-chart fc-width="600" fc-height="400" fc-type="pie3d", fc-datasource="{{dataSource}}">< /div>
As per the documentation we can use either of the ways.

**Comment by tanmay-mehrotra** [comment]
Also chart is not rendering properly ... all numeric values are distorted....using google chrome:(
However if I interact with the chart by clicking on it, everything becomes fine.
![3dpie](https://cloud.githubusercontent.com/assets/4707826/5594295/437d7b42-9213-11e4-8c69-6ca907100baf.jpg)

**Comment by AmeenAhmed** [comment]
Sorry for the delay @tanmay86. Will check it out.

**Comment by AmeenAhmed** [comment]
@tanmay86 I can confirm this works, If you see the demo for 3d pie in the demo browser at http://fusioncharts.github.io/angular-fusioncharts/#/demos/ex2, It uses the element name <fc-chart/> version, and it works. Can you tell me the angular.js version you are using?

**Comment by tanmay-mehrotra** [comment]
yeah , even I am amazed why it was not working for me when I am using it as an element rather than as an attribute. Using angular 1.2.16.

**Comment by ayanonly1** [comment]
@tanmay86 Sorry for the delay. Can you please share us a fiddle sample?

**Comment by ayanonly1** [comment]
Closing this issue. As this issue is inactive for a long time.
