### ISSUE TITLE
events is not firing with angular promise

### ISSUE THREAD

**Issue by shuklajay117** [fusioncharts/angularjs-fusioncharts#10]
I have 3 objects and all 3 component have pie chart. I want to capture `dataplotClick` event for all of them. I've created 3 datasource object and 3 events object for each. As datasource requires few dynamic values and for that I've to wait for my service response so I fill these both objects inside .then call back function. Chart is working fine but event is not working. If I move event object outside the then callback then it's working fine but in this case the same function will be calling for both chart click. Can anyone please help.

**Comment by ayanonly1** [comment]
Can you provide a jsfiddle sample on this?

**Comment by ayanonly1** [comment]
Closing this issue. As this issue is inactive for a long time.
