### ISSUE TITLE
Samples in documentation outdated

### ISSUE THREAD

**Issue by pmoelgaard** [fusioncharts/angularjs-fusioncharts#15]
The reference sample on the mainpage is invalid...
It needs to be updated to use the fc-chart / fc-chart-type / fc-data attributes.

**Comment by ayanonly1** [comment]
HI @pmoelgaard,

Thanks for your mail.

Can you please let me know where did you found these attributes?

**Comment by ayanonly1** [comment]
Hi @pmoelgaard ,

I am closing this issue as this is inactive for a long time. For any concern, please reply.
