### ISSUE TITLE
cannot load chart from json file 

### ISSUE THREAD

**Issue by vkanta** [fusioncharts/angularjs-fusioncharts#20]
Hi , I am having an issue loading a chart from my json file.
bellow is a copy of my scripts 
I can see the json file in firefox if I call on it 
also standard chart with data source in the $scope works fine 
only the external json file has issues 

I need the data to be external since I would like the file later to be generated via a script 
thank you in advance for the help 
Billy 
<json>
{
        chart: {
            caption: "Disk Space Usability",
            subcaption: "sv01",
            startingangle: "120",
            showlabels: "0",
            showlegend: "1",
            enablemultislicing: "0",
            slicingdistance: "15",
            showpercentvalues: "1",
            showpercentintooltip: "0",
            plottooltext: "Disk Uasage :  Total space : ",
            theme: "fint"
        },
        data: [
            {
                label: "Free space ",
                value: "214640357376"
            },
            {
                label: "size",
                value: "16613142528"
            }

```
    ]
```

}

</json> 
<html>
       <fusioncharts dataformat="jsonurl" datasource="data/data.json" type="pie3d" width="600" height="400"></fusioncharts>
</html>

**Comment by adotg** [comment]
Hey vkanta
Can you describe more about the 'issues'. I might also need you to explain how you feeding data to FusionCharts from the json file.

**Comment by vkanta** [comment]
i have figured it out the problem was the encoding on the json file
