### ISSUE TITLE
Bower.json and releases

### ISSUE THREAD

**Issue by deenairn** [fusioncharts/angularjs-fusioncharts#22]
Hello,

New to using fushion charts and would like to use them with angular.

I am a bit confused as to how it is anticipated that this module is redistributed. Is the idea that the source is downloaded from www.fushioncharts.com? 

Is there any chance you could add a bower.json file to enable download from Bower.io? This would enable developers to ensure that they have no dependency conflicts and would allow it to be added to their own Bower dependencies. A fork has been created which provides this but it is obviously not the official source:

https://github.com/adcuz/fc-angular-fusioncharts

In addition - is v3.1 an official release? It just appears to be a tag and yet it is linked from the official Fushion Charts GitHub IOwebsite.

http://fusioncharts.github.io/angular-fusioncharts/#/demos/ex1

But the download link on Fushion Charts website is only v3.0.

http://www.fusioncharts.com/downloads/plugins/angularjs-plugin.zip

Thanks,

Donald

**Comment by ThaDafinser** [comment]
+1 for bower. Needed in the modern frontend world

**Comment by achmad48** [comment]
Bower please..

**Comment by EricDosReis** [comment]
+1

**Comment by alinturbut** [comment]
+1 dependency management is a must for all libraries in a decent project.

**Comment by prithwirajfc** [comment]
Hi,

We've released v3.11.2 which now enables FusionCharts XT free trial to be downloaded via npm/Bower 
https://github.com/fusioncharts/fusioncharts-dist 

Also for more details on both visit the [Download page](http://www.fusioncharts.com/download/) or visit our [dev center](http://www.fusioncharts.com/dev/getting-started/installing-free-trial-via-npm-and-bower/installing-fusioncharts-suite-xt-via-npm-and-bower.html)

**Comment by AndrewEastwood** [comment]
+1

**Comment by ashok1994** [comment]
As we can now use bower to install fusioncharts , closing the issue for now
