### ISSUE TITLE
Compatible with latest Fusioncharts 3.9.0 

### ISSUE THREAD

**Issue by sabin30** [fusioncharts/angularjs-fusioncharts#23]
Hi,
My team is thinking to upgrade the fusioncharts to latest version i.e 3.9.0. Before we upgrade we like to make sure the angular-fusionharts.js file is compatible with the latest fusion chart version 3.9.0 or not.

Thanks
Sabin

**Comment by ayanonly1** [comment]
Hi Sabin,

Thank you for writing in to us.
Yes, this will be working with the latest FusionCharts release.
