### ISSUE TITLE
ConfigureLink for Drill-down chart

### ISSUE THREAD

**Issue by DoubleDP** [fusioncharts/angularjs-fusioncharts#27]
How do you call the ConfigureLink method to change the type for the drill-down chart?

**Comment by adotg** [comment]
Please check out official documentation [here](http://www.fusioncharts.com/dev/api/fusioncharts/fusioncharts-methods.html#configureLink) on configureLink. [This fiddle](http://jsfiddle.net/fusioncharts/zdewk96j/) shows how `type: "pie2d"` attribute can be used to change the drilldown type.

**Comment by DoubleDP** [comment]
I understand how the configureLink method works, but the implementation of it is via JavaScript. I am using the AngularJS plugin for FusionCharts and was wondering if there was a way to do that via the controller.

I have added some code to the angular-fusionchart directive that now executes the configureLink method if a value for the newly created attribute 'linkconfig' has been specified. Not sure if the implementation is 100% correct or if there is another way of doing it, but it works for now.

**Comment by adotg** [comment]
I see what you mean now.

Did you add code to the angularjs directive source code and made it work?

In that case you can send a pull request with your updated version. If somewhere the implementation needs to be changed we will update you with all the details. Cheers. :-)

**Comment by adotg** [comment]
Closing the issue as work around is available. You might also want to send a pull request of what you have done. We will be happy to look at it.
