### ISSUE TITLE
doughnut2d is rendering transparent fill

### ISSUE THREAD

**Issue by pvlreyes** [fusioncharts/angularjs-fusioncharts#29]
Not sure if I'm the only one having issue but doughnut2d is not rendering properly. the border has the correct pallet colors but the fill is transparent.

![fusionchart](https://cloud.githubusercontent.com/assets/4567504/13483280/066b2f22-e12e-11e5-8fd7-87df35fe8d71.PNG)

Here is my code:
html:
`<div width='100%' height='500' fusioncharts type="doughnut2d" datasource="{{datasource}}" ></div>`

js

`$scope.datasource = {
        "chart": {
                "caption": "Split of Revenue by Product Categories",
                "subCaption": "Last year",
                "numberPrefix": "$",
                "paletteColors": "#0075c2,#1aaf5d,#f2c500,#f45b00,#8e0000",
                "bgColor": "#ffffff",
                "showBorder": "0",
                "use3DLighting": "0",
                "showShadow": "0",
                "enableSmartLabels": "0",
                "startingAngle": "310",
                "showLabels": "0",
                "showPercentValues": "1",
                "showLegend": "1",
                "legendShadow": "0",
                "legendBorderAlpha": "0",
                "defaultCenterLabel": "Total revenue: $64.08K",
                "centerLabel": "Revenue from $label: $value",
                "centerLabelBold": "1",
                "showTooltip": "0",
                "decimals": "0",
                "captionFontSize": "14",
                "subcaptionFontSize": "14",
                "subcaptionFontBold": "0"
            },
            "data": [
                {
                    "label": "Food",
                    "value": "28504"
                }, 
                {
                    "label": "Apparels",
                    "value": "14633"
                }, 
                {
                    "label": "Electronics",
                    "value": "10507"
                }, 
                {
                    "label": "Household",
                    "value": "4910"
                }
            ]
    }`

**Comment by adotg** [comment]
By any chance, are you changing the default URL by using the `<base>` tag?

**Comment by pvlreyes** [comment]
Yes, I have <base href="/" />  in my html.

**Comment by adotg** [comment]
[This answer](http://stackoverflow.com/a/25713970/2474269) in stackoverflow might help you.

**Comment by pvlreyes** [comment]
Great. It is working now. Thanks a lot. :)
