### ISSUE TITLE
Supply data using .feedData()

### ISSUE THREAD

**Issue by tkt5025** [fusioncharts/angularjs-fusioncharts#31]
How can I supply data to my chart using the .feedData() function? 

I'd like to avoid running an additional server-side script to generate a single JSON file when I can easily make the API call to get data values using $http in angular.

**Comment by ayanonly1** [comment]
JSON file is not always required. You can directly send JSON data to the chart. And ". feedData" is applicable for the real time chart's only. If you are using this Angular plugin, then you don't have to think about the data update API's of FusionCharts, You have to just update the data in the scope of the chart directive only. You can refer to this [samle](http://www.fusioncharts.com/angularjs-charts/#/demos/ex6) for details. This sample update part of the data. But you can change the whole data and the chart will be updated.

**Comment by tkt5025** [comment]
I have tried the method of updating only the scope. This does update the chart but re-draws the chart element. What I was hoping for is that each data point would be added without disrupting the chart element.
We have 2 hrs of data being updated every minute so the chart gets redrawn every minute. Instead, I'd like to use something like .feedData() so that only the newest point is added to the chart.

**Comment by ayanonly1** [comment]
There might be various way for this-
- Use id in chart (directive attribute "chartid") and access the chart using FusionCharts("your_chart_id") and then you can use the .feedData of that.
- Add the data in the datasource of the controller and set animation ='0' in the chart's configuration.

If this does not work, please send us a simple sample or jsfiddle link of your chart.

**Comment by tkt5025** [comment]
I've used animation=0 and that seems to be working! Thanks!
