### ISSUE TITLE
barchart not rendering with contentString with Google Maps

### ISSUE THREAD

**Issue by hillaryskye** [fusioncharts/angularjs-fusioncharts#32]
I have the column2d bar chart all figured up, but the graph is not rendering.  I have put the html in a contentString as part of a directive.  Here is the part where I added it to the contentString:

var contentString = '<h4>' + marker[i].name + '</h4><br>' +
            marker[i].address + '<br>';
            if (typeof marker[i].phone !== 'undefined') contentString += 'Phone: ' + marker[i].phone + '<br>'
            if (typeof marker[i].website !== 'undefined') contentString += 'Website: <a target="_blank" href="' + marker[i].website + '">' + marker[i].name + '</a><br>';
            if (typeof marker[i].rating !== 'undefined') contentString += 'Rating: ' + marker[i].rating + '<br>';
            if (typeof marker[i].priceLevel !== 'undefined') contentString += '<fusioncharts width="100" height="20" type="column2d" dataSource="{{dataSource}}"></fusioncharts><br>';
            if (typeof marker[i].rating !== 'undefined') contentString += 'User Ratings: ' + ratingStars + '<br>';

Here is the part where I declare the data for the graph:

if (marker[i].priceLevel) {
            debugger;
            $scope.dataSource = {
                "chart": {
                    "caption": "Pricing",
                    "captionFontSize": "15",
                    "bgColor": "#00f987",
                    "showAxisLines": "1",
                    "xAxisName": "Price Level",
                    "toolTipColor": "#ffffff",
                    "axisLineAlpha": "85",
                    "xAxisLineColor": "#000",
                    "showHoverEffect": "1",
                    "animation": "1"
                },
                "data": [{
                    "label": "Price Level",
                    "value": "marker[i].priceLevel",
                    "showLabel": "1",
                    "showValue": "1"
                  }]
              }
          }

I have tried it with the <div fusionchart as well as just <fusionchart and neither works.  Wondering what you suggest?

**Comment by adotg** [comment]
Please validate my assumptions
- `marker` is an array of objects
- `i` is the iteration index of the loop

If that is the case 
Is `$scope.dataSource = { ... }` is getting executed inside a loop?

**Comment by hillaryskye** [comment]
Yes, I am running a loop for dynamic google map markers

**Comment by adotg** [comment]
Closing the issue because the issue was in the basic javascript use.
