### ISSUE TITLE
Best practice for loading multiple( more than 10 ) pie/zoomline in (fusion chart js API + Angular js)

### ISSUE THREAD

**Issue by akilanvit** [fusioncharts/angularjs-fusioncharts#34]
Is there any other best option for loading multiple chart with good performance (avoid browser overload, comfort user interaction)

According to analysis, rendering multiple (pie/zoomline) charts with synchronous way like using ajax call (first chart completed after then rest of charts one by one) .I dont know exactly this one is good way or not.

please suggest me which one is best way to follow this kind of usecase without major drawbacks

**Comment by rousan** [comment]
@akilanvit 
The best solution will be rendering charts one by one because charts are rendered asynchronously and they do not block each other.
please look at this [fiddle](https://jsfiddle.net/ariyankhan/k1ko2vyt/).
