### ISSUE TITLE
The hidden fusionchart doesn't update

### ISSUE THREAD

**Issue by AlexBrel** [fusioncharts/angularjs-fusioncharts#36]
Hi, I have a trouble with fusionchart. When I hide it using an angular ng-hide, my fusionchart stops any updating. As a result, if I show it again, my chart is outdated.

I’ve created a Codepen page with an example, you can play with it:
http://codepen.io/AlexBrel/pen/JRbPYb

Could you please suggest anything to resolve my issue?

Thank you in advance,
Alex

**Comment by ashok1994** [comment]
It works with the latest version
https://codepen.io/askipop/pen/vzqJZx

Please reopen if the problem persists
