### ISSUE TITLE
How can I change the attribute in dataset of Fusionchart?

### ISSUE THREAD

**Issue by usman10scorpio** [fusioncharts/angularjs-fusioncharts#37]
Hi I am implementing a chart in my Angularjs Application, You can see this plunker `http://jsfiddle.net/fusioncharts/73xgmacm/`The thing which I want to achieve is to change the `value`attribute to `profit`. How can I do this ? I want to display profit not values.

Regards

**Comment by soumyasankarduttagit** [comment]
Yes, you need to set **showValues** attribute as 0  for which data series the value needs to be hidden and for the series (profit in your case) please set **showValues** attribute as 1. For further reference please check the modified fiddle http://jsfiddle.net/Soumya_dutta/136sh6uc/11/

**Comment by ashok1994** [comment]
@usman10scorpio  Can you please elaborate what you mean by "change the `value` attribute to `profit`"

**Comment by ashok1994** [comment]
Closing for now , feel free to reopen if any doubts
