### ISSUE TITLE
state change when chart is in hidden tab

### ISSUE THREAD

**Issue by iftekharulislam** [fusioncharts/angularjs-fusioncharts#38]
I have a simple application where the fusion chart is inside a bootstrap tab. When I try to switch state from one (that have the bootstrap tab and chart is in the hidden tab, i.e: no selected that time) to another, there occurs a console error.

steps to reproduce
* click **About** then click **Home** you'll find the console error. The chart was inside the **About** states profile tab which we didn't click. so the problem is if our chart is inside a hidden div and we try to switch state, the error rises.

The demo application is attached here.
https://embed.plnkr.co/oX8tEWz3d9Er6N0A5KxB/

**Comment by ashok1994** [comment]
@iftekharulislam 
Sorry for the late reply, 
this plunkr seems tp work with the latest fusioncharts
and angular-fusioncharts
https://embed.plnkr.co/oX8tEWz3d9Er6N0A5KxB/

Closing for now , feel free to reopen it , if the problem persists
