### ISSUE TITLE
Poor documentation

### ISSUE THREAD

**Issue by ToothpickFactory** [fusioncharts/angularjs-fusioncharts#4]
I have followed the steps found in your guide to get the application running. I am unable to get the chart to display. Will please provide a jsbin on how to get a very simple version of angular-fusioncharts working?

**Comment by shamasis** [comment]
Did you refer to http://fusioncharts.github.io/angular-fusioncharts/#/demos/ex1 ?

**Comment by marklombardi** [comment]
I agree with the initial comments. I have followed the instructions [here](http://www.fusioncharts.com/angularjs-charts/), [here](https://fusioncharts.github.io/angular-fusioncharts/#/demos/ex1) and [here](http://docs.fusioncharts.com/tutorial-using-with-javascript-libraries-angularjs-creating-charts-using-the-angular-fusioncharts-plugin.html) and am still unable to get a chart to render.

Please provide a full working sample. 

The snippets provided in the above links conflict with each other as well. e.g. Is the latest directive &lt; fusioncharts&gt; or &lt;fc-chart&gt;?

**Comment by marklombardi** [comment]
This post on the fusioncharts forum resolved my problem [angular-fusioncharts](http://forum.fusioncharts.com/topic/16708-angular-fusion-charts-not-loading/?hl=angularjs#entry61831)

Sample files: [dropbox](https://www.dropbox.com/s/q29xvww4n9cp7tv/angular_New_Test.rar?dl=0)

**Comment by ToothpickFactory** [comment]
Awesome, I appreciate that.
