### ISSUE TITLE
Uncaught TypeError: Cannot read property 'nodeType' of null

### ISSUE THREAD

**Issue by devfxplayer** [fusioncharts/angularjs-fusioncharts#40]
Hi,
I get this
Uncaught TypeError: Cannot read property 'nodeType' of null

What is it?

**Comment by rousan** [comment]
@devfxplayer 
can you please provide a code sample to reproduce the same issues at our end?

**Comment by devfxplayer** [comment]
please close this ticket

**Comment by bagasprakarso** [comment]
hi @devfxplayer i have same problem,
could you share to me how to fix it?

Thanks
