### ISSUE TITLE
Pie charts are black on Safari and Firefox

### ISSUE THREAD

**Issue by jidesakin** [fusioncharts/angularjs-fusioncharts#42]
The charts work well on Chrome browser. I just discovered that the pie charts are black on Safari and Firefox. The column charts display well across other browsers.

<img width="1109" alt="screen shot 2017-04-20 at 11 41 50" src="https://cloud.githubusercontent.com/assets/3943697/25226879/61bf0bde-25be-11e7-8c70-0c479c08da57.png">

**Comment by rousan** [comment]
Hi @jidesakin 
please use the following code snippet before rendering any chart in Safari:
```javascript
FusionCharts.options.SVGDefinitionURL='absolute';
```
