### ISSUE TITLE
Disposing logic

### ISSUE THREAD

**Issue by jasmh** [fusioncharts/angularjs-fusioncharts#46]
Why isn't this merged?

https://github.com/fusioncharts/angular-fusioncharts/pull/33

I concluded that I need this exact change in my code and added it before I even looked at the issues and found this PR. It prevents memory leaks and I think it sometimes may prevent unexpected errors like 'nodeType is null' as the chart is not disposed when the DOM element is removed.

**Comment by rousan** [comment]
Hi @jasmh,
The problem described in #33 PR is already resolved and will be available in next patch version soon, so we should close this PR as well as this issue.
Thanks.

**Comment by jasmh** [comment]
Would you care to elaborate a bit more? I don't see any new commits to angular-fusioncharts. Is it handled internally by fusioncharts? If yes, in which version?

**Comment by rousan** [comment]
Hi @jasmh 
We resolved this issue and the patch version for this issue will be released soon.

**Comment by ashok1994** [comment]
@jasmh  The pull request is merged now , will be available in next patch release 4.0.3.
Closing for now .
