### ISSUE TITLE
Country Map not centered

### ISSUE THREAD

**Issue by kenshinman** [fusioncharts/angularjs-fusioncharts#49]
Hi, Using this angular plugin to display country map but the state labels are displaying where they should but the map regions are down to the bottom right of the container div. How can this be resolved please?
Thanks

**Comment by ashok1994** [comment]
Sorry for replying late,  Can you provide a scale down sample if the issue still persists @kenshinman

**Comment by ashok1994** [comment]
Closing for now, please feel free to reopen if issue still persists
